### ISSUE TITLE
Use API Key

### ISSUE THREAD

**Issue by doggy8088** [kiranvshah/chatgpt-helper#14]
Please don't use OpenAI username and password, use the API Key instead.

https://beta.openai.com/account/api-keys

**Comment by kiranvshah** [comment]
as far as I understand, the OpenAI API doesn't work for ChatGPT yet, but I plan on using [this](https://github.com/transitive-bullshit/chatgpt-api) unofficial API in the future, which uses session tokens instead of username & password

**Comment by kiranvshah** [comment]
will be fixed by #17
