### ISSUE TITLE
How to Cange API Key?

### ISSUE THREAD

**Issue by chreiter** [kiranvshah/chatgpt-helper#25]
Hi Dave,
I entered a wrong API Key. How can I change this?

**Comment by kiranvshah** [comment]
there's currently no functionality to change your api key - i'll build it in to the extension and release an update today :)

**Comment by kiranvshah** [comment]
I've added a command `ChatGPT: Change OpenAI API key` in v3.1.0 (now released). reloading vs code should install the update

**Comment by chreiter** [comment]
Thanks sooo much. works fine!!! Happy New Year!

**Comment by chreiter** [comment]
So I tryed now to ask ChatPGT to write a code for me inside VCcode, but the answers return no code, but just normal flat text messages. This is total diffenent than asking ChatGPT for Code on the openAI WebSite. What I am making worng? Thanks

**Comment by kiranvshah** [comment]
> Thanks sooo much. works fine!!! Happy New Year!

you're welcome, thanks for the suggestion! happy new year too :)
