### ISSUE TITLE
difficulty installing: click install page on marketplace not working

### ISSUE THREAD

**Issue by jb1567us** [kiranvshah/chatgpt-helper#27]
Having trouble here. I downloaded the package, but where do i put it in VStudio 2022?

**Comment by kiranvshah** [comment]
Hi there,
This is an extension for Visual Studio Code, not Visual Studio 2022. If you are using VS Code, clicking the Install button on [the marketplace page](https://marketplace.visualstudio.com/items?itemName=kiranshah.chatgpt-helper) should open the appropriate install page inside VS Code.

**Comment by kiranvshah** [comment]
closed due to inactivity
