### ISSUE TITLE
Cannot find and use the extension

### ISSUE THREAD

**Issue by ZinaL88** [kiranvshah/chatgpt-helper#36]
I installed and enabled the extension, but it doesn't show in the extension sidebar, even the deprecated shows. So now I cannot use the chatgpt helper, even though I tried to reinstall or enable it several times.

![image](https://user-images.githubusercontent.com/30545414/230262387-46c827e9-82d0-4b5b-bda8-4df61ad90336.png)

**Comment by kiranvshah** [comment]
Hi, thanks for reaching out. This extension does not (yet) have a tab in the primary sidebar - instead, it is used by selecting some code inside the editor, right-clicking and selecting "ChatGPT: Ask why code isn't working" or "ChatGPT: Ask to explain code". Alternatively, you can run the "ChatGPT: Ask a question" command from the command palette. Refer to the [README](https://github.com/kiranvshah/chatgpt-helper/blob/main/README.md#features) for more info on how to use the extension.
