### ISSUE TITLE
how to select entire project engine to ask question

### ISSUE THREAD

**Issue by Vaishnavi21721** [kiranvshah/chatgpt-helper#42]

**Comment by kiranvshah** [comment]
I don't quite understand what you're asking - could you please elaborate?

**Comment by Vaishnavi21721** [comment]
let suppose, I am having my project folder opened in vs code with the codegpt. Only I can select the code from particular file and ask questions to gpt. but if I want to ask questions on my entire project, so I could I do that?

**Comment by kiranvshah** [comment]
this is not yet possible with the extension, sorry
